version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

volumes:
  pgdata:
